<?php

namespace Fose\FoseBundle\Entity;

/**
 * abonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abonneRepository extends \Doctrine\ORM\EntityRepository
{
}
