<?php

namespace Fose\FoseBundle\Entity;

/**
 * article_catergorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articlecatRepository extends \Doctrine\ORM\EntityRepository
{
}
