<?php

namespace Fose\FoseBundle\Entity;

/**
 * EnligneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnligneRepository extends \Doctrine\ORM\EntityRepository
{
}
