<?php

namespace Fose\FoseBundle\Entity;

/**
 * image_catRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imagecatRepository extends \Doctrine\ORM\EntityRepository
{
}
